### ISSUE TITLE
error scanning /usr/src/eventbridge-atlas/generated-docs: yaml: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by metaskills** [boyney123/eventbridge-atlas#1]
This is what I saw when trying to start the server. Could it be there are no event rules on my bus?

```
2021/04/29 02:47:43 Docuowl v0.2
2021/04/29 02:47:43 Rendering contents...
2021/04/29 02:47:43 error scanning /usr/src/eventbridge-atlas/generated-docs: yaml: mapping values are not allowed in this context

> eventbridge-atlas@0.0.1 add-event-atlas-ui-changes /Users/kencollins/Repositories/eventbridge-atlas
> babel-node src/add-event-atlas-ui-changes.js

(node:57047) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/kencollins/Repositories/eventbridge-atlas/docs-html/index.html'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at _callee$ (/Users/kencollins/Repositories/eventbridge-atlas/src/add-event-atlas-ui-changes.js:7:19)
    at tryCatch (/Users/kencollins/Repositories/eventbridge-atlas/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/kencollins/Repositories/eventbridge-atlas/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/kencollins/Repositories/eventbridge-atlas/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/kencollins/Repositories/eventbridge-atlas/src/add-event-atlas-ui-changes.js:13:103)
    at _next (/Users/kencollins/Repositories/eventbridge-atlas/src/add-event-atlas-ui-changes.js:15:194)
    at /Users/kencollins/Repositories/eventbridge-atlas/src/add-event-atlas-ui-changes.js:15:364
    at new Promise (<anonymous>)
(node:57047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by boyney123** [comment]
Hey @metaskills 

Yeah this seems abit odd, I'm going to do a release of 0.2 today, so if you could try that to see if it would fix it? 

Hopefully out today!

**Comment by boyney123** [comment]
Going to close for now, been a couple of weeks. If you still have issues just let me know
