### ISSUE TITLE
Unsupported operation exception thrown when generating meta-data

### ISSUE THREAD

**Issue by mariuszch** [boyney123/eventbridge-atlas#13]

**Comment by mariuszch** [comment]
When I setup .env file and run generate-eventmetadata I get exception:

m.chruscielewski@LE2273 eventbridge-atlas % npm run generate-eventmetadata

> eventbridge-atlas@1.1.0 generate-eventmetadata
> babel-node src/utils/generate-metadata-templates

/Users/m.chruscielewski/projects/growy/eventbridge-atlas/node_modules/@aws-sdk/client-schemas/dist-cjs/protocols/Aws_restJson1.js:2362
    const exception = new models_0_1.BadRequestException({
                      ^

BadRequestException: Unsupported operation.
    at deserializeAws_restJson1BadRequestExceptionResponse (/Users/m.chruscielewski/projects/growy/eventbridge-atlas/node_modules/@aws-sdk/client-schemas/dist-cjs/protocols/Aws_restJson1.js:2362:23)
    at deserializeAws_restJson1ListSchemasCommandError (/Users/m.chruscielewski/projects/growy/eventbridge-atlas/node_modules/@aws-sdk/client-schemas/dist-cjs/protocols/Aws_restJson1.js:1693:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/m.chruscielewski/projects/growy/eventbridge-atlas/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at /Users/m.chruscielewski/projects/growy/eventbridge-atlas/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at StandardRetryStrategy.retry (/Users/m.chruscielewski/projects/growy/eventbridge-atlas/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at /Users/m.chruscielewski/projects/growy/eventbridge-atlas/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '65e87a6e-c438-45c9-b977-f364c7dd46ef',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'MalformedRequest'
}

**Comment by boyney123** [comment]
Hmm looks like `400` error, what schema registry have you entered in the env file? Might be worth double checking region, schema reg and event bus in the env file is setup correctly.

**Comment by ekaanresangsya** [comment]
Any solution for this issue? I got same problem too. I'm pretty sure my env is correct
